image: docker

services:
    - docker:bind

stages:
    - test
    - deploy

test:
    stage: test
    only: 
        - master
    script:
        - cd ./backend
        - npm run test

step-deploy-prod:
    stage: deploy
    only:
        - master
    script: 
        - sudo apt-get install -y python-pip
        - pip install docker-compose
        - make start-production
    environment: production
    when: manual