version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - ${DB_HOST}
    depends_on:
      - ${DB_HOST}
    environment:
      WAIT_HOSTS: mongo:${DB_PORT}
  mongo:
    container_name: ${DB_HOST}
    image: mongo
    user: mongodb
    volumes:
      - /tmp/expressts:/data/db
      - .:/usr/src/app
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: mongod --smallfiles
