# all variables used in this file are defined in the .env file
version: "2"
services:
  node-app-0:
    container_name: ${CONTAINER_NAME_1}
    restart: always
    build: ./backend
    links:
      - ${DB_HOST}
    depends_on:
      - ${DB_HOST}
    environment:
      WAIT_HOSTS: mongo:${DB_PORT}
      WAIT_HOSTS_TIMEOUT: 150
      ROLE: MASTER
      HOST: ${CONTAINER_NAME_1}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SERVER_PORT: ${SERVER_PORT}
      BASIC_AUTH_USER=: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
  # node-app-1:
  #   container_name: ${CONTAINER_NAME_2}
  #   restart: always
  #   build: ./backend
  #   links:
  #     - ${DB_HOST}
  #   depends_on:
  #     - ${DB_HOST}
  #   environment:
  #     WAIT_HOSTS: mongo:${DB_PORT}
  #     WAIT_HOSTS_TIMEOUT: 150
  #     HOST: ${CONTAINER_NAME_2}
  #     DB_HOST: ${DB_HOST}
  #     DB_PORT: ${DB_PORT}
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #     SERVER_PORT: ${SERVER_PORT}
  #     BASIC_AUTH_USER=: ${BASIC_AUTH_USER}
  #     BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
  frontend:
    container_name: ${CONTAINER_NAME_FRONTEND}
    build: ./frontend
  mongo:
    container_name: ${DB_HOST}
    image: mongo
    user: mongodb
    volumes:
      - node-ts-volume:/data/db
      - .:/usr/src/app
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: mongod --smallfiles
  loadbalancer:
      build: ./nginx
      tty: true
      links:
          - ${CONTAINER_NAME_1}
          # - ${CONTAINER_NAME_2}
      ports:
          - '8080:8080'
      depends_on:
      - ${CONTAINER_NAME_1}
      # - ${CONTAINER_NAME_2}
volumes:
  node-ts-volume:
        external: true